-- Portfolio community schema for Vercel + Supabase.
-- Run this once in Supabase SQL Editor on a new project.

create table if not exists public.users (
  id text primary key,
  name text not null,
  email text not null unique,
  "passwordSalt" text not null,
  "passwordHash" text not null,
  "authVersion" integer not null default 1 check ("authVersion" >= 1),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  "authorId" text not null references public.users(id) on delete cascade,
  slug text not null,
  title text not null,
  year text not null,
  category text not null,
  summary text not null default '',
  context text not null default '',
  concept text not null default '',
  tags text not null default '[]',
  tone text not null default 'tone-ink',
  status text not null default 'draft' check (status in ('draft', 'published')),
  featured boolean not null default false,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  unique ("authorId", slug)
);

create table if not exists public.project_images (
  id bigint generated by default as identity primary key,
  "authorId" text not null references public.users(id) on delete cascade,
  "projectId" bigint not null references public.projects(id) on delete cascade,
  "objectKey" text not null unique,
  "altText" text not null default '',
  "sortOrder" integer not null default 0,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.profiles (
  "authorId" text primary key references public.users(id) on delete cascade,
  "roleZh" text not null default '',
  intro text not null default '',
  focus jsonb not null default '[]'::jsonb,
  education text not null default '',
  experience text not null default '',
  awards text not null default '',
  "imageKey" text not null default '',
  "imageKeys" jsonb not null default '[]'::jsonb
);

create table if not exists public.contact_links (
  "authorId" text not null references public.users(id) on delete cascade,
  id text not null,
  kind text not null check (kind in ('email', 'social', 'portfolio', 'other')),
  label text not null,
  value text not null,
  href text not null default '',
  "sortOrder" integer not null default 0,
  primary key ("authorId", id)
);

create table if not exists public.email_codes (
  id text primary key,
  email text not null,
  purpose text not null check (purpose in ('register', 'reset')),
  "codeSalt" text not null,
  "codeHash" text not null,
  attempts integer not null default 0,
  "expiresAt" timestamptz not null,
  "createdAt" timestamptz not null default now(),
  "usedAt" timestamptz
);

create table if not exists public.otp_send_attempts (
  id text primary key,
  email text not null,
  ip text not null,
  purpose text not null check (purpose in ('register', 'reset')),
  sent boolean not null default false,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.login_attempts (
  id text primary key,
  email text not null,
  ip text not null,
  success boolean not null default false,
  "createdAt" timestamptz not null default now()
);

create index if not exists projects_author_status_idx on public.projects ("authorId", status, "updatedAt" desc);
create index if not exists project_images_project_idx on public.project_images ("projectId", "sortOrder", id);
create index if not exists email_codes_lookup_idx on public.email_codes (email, purpose, "createdAt" desc);
create index if not exists otp_send_attempts_email_idx on public.otp_send_attempts (email, "createdAt" desc);
create index if not exists otp_send_attempts_ip_idx on public.otp_send_attempts (ip, "createdAt" desc);
create index if not exists login_attempts_email_idx on public.login_attempts (email, "createdAt" desc);
create index if not exists login_attempts_ip_idx on public.login_attempts (ip, "createdAt" desc);

-- Browser clients never receive the server secret. Keep all tables private and let
-- the Vercel server use the Supabase secret key for authorized operations.
alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.project_images enable row level security;
alter table public.profiles enable row level security;
alter table public.contact_links enable row level security;
alter table public.email_codes enable row level security;
alter table public.otp_send_attempts enable row level security;
alter table public.login_attempts enable row level security;

-- Private object bucket. Uploads first land in tmp/<user>/..., are validated by
-- the app server, then copied to media/<key>. No public bucket policy is created.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'portfolio-media',
  'portfolio-media',
  false,
  15728640,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
