-- Project video media support.
-- Run this after 001_initial.sql and 002_registration_capacity.sql.

create table if not exists public.project_videos (
  id bigint generated by default as identity primary key,
  "authorId" text not null references public.users(id) on delete cascade,
  "projectId" bigint not null references public.projects(id) on delete cascade,
  "objectKey" text not null unique,
  "altText" text not null default '',
  "sortOrder" integer not null default 0,
  "createdAt" timestamptz not null default now()
);

create index if not exists project_videos_project_idx on public.project_videos ("projectId", "sortOrder", id);
create index if not exists project_videos_author_idx on public.project_videos ("authorId", "createdAt" desc);

alter table public.project_videos enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'portfolio-media',
  'portfolio-media',
  false,
  209715200,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'video/mp4',
    'video/webm',
    'video/quicktime',
    'video/x-m4v'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
